### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pascalandy** [dcefram/stupendous#4]
Can't load any pages.

<img width="1051" alt="screen shot 2017-08-12 at 10 52 11 am" src="https://user-images.githubusercontent.com/6694151/29241681-54acb440-7f4c-11e7-9819-40d2d0b218bc.png">

Cheers!

**Comment by ghost** [comment]
I'll look into this right now. Must be an issue with me blindly supporting v1.x by relying on https://gscan.ghost.org. Thanks for reporting.

**Comment by ghost** [comment]
This should work now. [2.0.1](https://github.com/dcefram/Stupendous/tree/2.0.1)
