### ISSUE TITLE
Error 500: [index.hbs] Cannot read property 'includeZero' of undefined

### ISSUE THREAD

**Issue by EweSparky** [dcefram/stupendous#5]
I get an error 500 ("[index.hbs] Cannot read property 'includeZero' of undefined") when I activate this theme in Ghost(Pro).

**Comment by ghost** [comment]
I'll look into that right now. I'm currently still running in Ghost version 0.11.x, but I decided to support v1.x using https://gscan.ghost.org/. But it seems not to work out of the box, I'll look into that right now, thanks for reporting.

**Comment by ghost** [comment]
This should be fixed in v2.0.1

https://github.com/dcefram/Stupendous/tree/2.0.1
